name: akari_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  share_plus: ^9.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/shop_items/
    - assets/music/
  fonts:
    - family: "Chonky Cat"
      fonts:
        - asset: assets/fonts/Chonky-Cat.ttf
    - family: "Mc Ten"
      fonts:
        - asset: assets/fonts/Mc-Ten.ttf
    - family: "Manga"
      fonts:
        - asset: assets/fonts/Manga.otf
    - family: "Steamwheel"
      fonts:
        - asset: assets/fonts/Steamwheel.otf